version: '2'
services:
  reverse_proxy:
    container_name: cabfront_reverse_proxy
    image: nginx:alpine
    networks:
      - frontnet
    ports:
     - "80:80"
     - "443:443"
    restart: always
    volumes:
     - /docker-volumes/cabfront-conf.d:/etc/nginx/conf.d
     - /docker-volumes/cabfront-certs:/etc/certs/nginx
  cab:
    command: ["generate", "--signal", "HUP", "cabfront_reverse_proxy", "--watch", "--output-file", "/etc/nginx/conf.d/docker-cab.conf", "/templates/nginx.tpl"]
    image: mbr0/docker-cab:stable
    networks: []
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /docker-volumes/cabfront-conf.d:/etc/nginx/conf.d
    depends_on:
      - reverse_proxy
networks:
  frontnet:
    external:
      name: frontnet
